language: node_js

node_js:
  - "12.9.0"

install:
  - npm run clean:all
  - npm run bootstrap:no-lock

script:
  - npm run test

jobs:
  include:
    - stage: Produce Coverage
      node_js: "12.9.0"
      script: npm run test && node coveralls-merge.js && cat ./lcov.info | ./node_modules/coveralls/bin/coveralls.js
