import {isDecorator} from "./metadata";

export {
  IMetadata,
  defineMetadata,
  getMetadata,
  getOwnMetadata,
  getMetadataKeys,
  getOwnMetadataKeys,
  hasOwnMetadata,
  hasMetadata,
  getDecoratorName,
  getDecoratorType,
  getDecoratorUUID,
  getDecoratorId,
  createClassDecorator,
  createPropertyDecorator,
  createParameterDecorator,
  createParameterAndPropertyDecorator,
  createMethodDecorator,
  hasDecorator,
  isDecorator,
  getClassMetadata,
  getPropertyMetadata,
  getMethodMetadata,
  getParameterMetadata,
  getMetadataKeysForTarget,
  getMetadataForTarget,
  getAllKeysForTarget,
  getAllMetadataKeysForTarget,
  getAllMetadataForTarget,
  TS_PARAMS,
  TS_RETURN,
  TS_TYPE
} from "./metadata";
