version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm run bootstrap
  - &build-packages
    run:
      name: Build
      command: npm run build
  - &run-unit-tests
    run:
      name: Test
      command: npm run test

unit-tests-template: &unit-tests-template
  working_directory: ~/tpx
  steps:
    - checkout
    - *restore-cache
    - *install-deps
    - *build-packages
    - *run-unit-tests

jobs:
  build:
    working_directory: ~/tpx
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@^8'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test_node_18:
    <<: *unit-tests-template
    docker:
      - image: cimg/node:18.16

  test_node_lts:
    <<: *unit-tests-template
    docker:
      - image: cimg/node:lts

  test_node_latest:
    <<: *unit-tests-template
    docker:
      - image: cimg/node:current

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test_node_18:
          requires:
            - build
      - test_node_lts:
          requires:
            - build
      - test_node_latest:
          requires:
            - build
