name: typeix build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Clean Install
        run: npm ci
      - name: Install Packages
        run: npm run bootstrap
      - name: Typeix Build
        run: npm run build
      - name: Typeix Test
        run: npm run test:ci
      - name: Typeix Coverage
        run: npm run coveralls-merge
      - name: Publish Typeix Coverage
        uses: coverallsapp/github-action@v2

